1  make ebooks unique
Lullabot/lb-ebook-poc pull request #4
Opened 2024-06-08 00:19 UTC by sirkitree

This was a beast.

In short terms the relevant pieces are:
* a different way to create a multidimensional array of books and their chapters
* some custom pagination because eleventy pagination out of the box doesn't support multidimensional arrays
* a more standard approach to using templates rather than conditionally including them based on pagination
* blood sweat and tears

Note that this is based on my first pull request, so you'll want to merge that first.

2024-06-08 00:23 UTC, sirkitree commented
or perhaps this has all those changes, so maybe just merge this one? i don't git much these days so i perhaps messed up branching

2024-06-10 21:25 UTC, huntermacd requested changes
I noticed for the `my-sample-ebook` has only two chapters but there are three items in the TOC and you can reach chapter three which is just chapter again but without any styling.

Added some questions and suggestions. Otherwise, looks great! I'm able to add another ebook to the directory and it shows up in on the site with proper page ordering. Great work!

2024-06-10 21:25 UTC, huntermacd commented on package.json
> +    "sharp": "^0.33.4"
Is this being used? I think `eleventy-img` already provides this utility.

2024-06-10 21:25 UTC, huntermacd commented on src/_includes/layout.liquid
> +          <div><a href="/ebooks/{{ bookWithChapters.book.slug }}/table-of-contents">TOC</a></div>
We want this to be blank on the cover, say "TOC" on the TOC, and switch to page number for the chapters.

2024-06-10 21:25 UTC, huntermacd commented on src/ebooks/.DS_Store
This file can be removed. Maybe we can add `.DS_Store` to the `.gitignore`.

2024-06-10 21:25 UTC, huntermacd commented on src/ebooks/my-sample-ebook/chapters/chapter-2.md
> +layout: chapter
Let's use the `.liquid` extension when specifying the layout everywhere or remove them everywhere for consistency.

2024-06-11 13:05 UTC, sirkitree commented on package.json
> +    "sharp": "^0.33.4"
I'm honestly not sure, but originally when I first cloned the repo and tried to `npm install` I kept getting an error about this and couldn't proceed until I installed it. 🤷

2024-06-11 13:06 UTC, sirkitree commented on src/_includes/layout.liquid
> +          <div><a href="/ebooks/{{ bookWithChapters.book.slug }}/table-of-contents">TOC</a></div>
Ah, ok. I thought it was meant to be a quick way to get back to the TOC.

2024-06-11 13:23 UTC, sirkitree commented on src/ebooks/.DS_Store
ah, yes I think I removed this in my subsequent PR

2024-06-11 13:30 UTC, sirkitree commented
> I noticed for the my-sample-ebook has only two chapters but there are three items in the TOC and you can reach chapter three which is just chapter again but without any styling.
![Monosnap Table of Contents 2024-06-11 06-30-22](https://github.com/Lullabot/lb-ebook-poc/assets/28543/c4054d18-321e-452d-b188-1ca11c7faa07)


I'm not seeing this...

2024-06-11 13:31 UTC, sirkitree commented
addressed all suggestions above - please re-review.

2024-06-11 16:38 UTC, huntermacd commented on package.json
> +    "sharp": "^0.33.4"
Hm. Fair enough. :)

2024-06-11 16:38 UTC, huntermacd commented on src/ebooks/.DS_Store
Still here. :D

2024-06-11 16:40 UTC, huntermacd reviewed
Looks great! Still seeing that .DS_Store file. Remove that and we can :shipit:.

2024-06-11 16:41 UTC, huntermacd commented
If you delete the _site directory and rebuild, do you still not see the erroneous third chapter for the sample ebook?

2024-06-11 22:24 UTC, sirkitree commented on src/ebooks/.DS_Store
hrm, wtf... I don't have one locally... and if I do a fresh checkout it doesn't create one. I'm not sure how to remove this...

2024-06-11 22:27 UTC, sirkitree commented
Correct, if I delete `_site`, `npm run build`, and then close down the server and restart it with `npm run start` I get this: 
![image](https://github.com/Lullabot/lb-ebook-poc/assets/28543/21e8387d-a44c-46ca-b0d3-5fd5846ba514)

2024-06-13 18:16 UTC, merged

2024-06-13 18:17 UTC, sirkitree commented
merging so I can keep building