Add new ebook - Why Your CMS Project Will Fail
Lullabot/lb-ebook-poc pull request #74
Opened 2024-09-16 21:09 UTC by jazzdrive3

So far this has only the text and not the images.

2024-09-17 02:07 UTC, sirkitree requested changes
I know you're still working on it, but thought I'd give some feedback early.

2024-09-17 02:07 UTC, sirkitree commented on src/ebooks/why-your-cms-will-fail/chapters/chapter-2.md
> +title: 'One: A lack of stakeholder involvement'
Chapters are currently numbered automatically, so this sort of looks funny on the table of contents:
https://pr74-dex8gkuvg6cggqol1lwasfiqtddsrwez.tugboatqa.com/ebooks/why-your-cms-will-fail/table-of-contents/
![image](https://github.com/user-attachments/assets/78194ac7-2ec6-47dd-8309-d9a2361fe0a3)

2024-09-17 02:07 UTC, sirkitree commented on src/ebooks/why-your-cms-will-fail/chapters/chapter-2.md
> +title: 'One: A lack of stakeholder involvement'
Kinda reads funny on the actual pages as well
![image](https://github.com/user-attachments/assets/bdded6e2-3e1e-4736-8a79-50d0c6568ee6)

2024-09-17 02:07 UTC, sirkitree commented on src/ebooks/why-your-cms-will-fail/chapters/chapter-7.md
> +title: 'Five: Not knowing how to use the system'
![image](https://github.com/user-attachments/assets/f5d088b5-706e-4389-bed2-d4c65522b42e)

2024-09-17 02:07 UTC, sirkitree commented on src/ebooks/why-your-cms-will-fail/index.html
> +title: "Sample eBook"
I suggest putting the actual title here as well.

2024-09-17 03:56 UTC, jazzdrive3 commented on src/ebooks/why-your-cms-will-fail/chapters/chapter-2.md
> +title: 'One: A lack of stakeholder involvement'
This is related to an issue I opened about how this currently works.

https://github.com/Lullabot/lb-ebook-poc/issues/72

2024-09-26 21:32 UTC, sirkitree approved these changes
i think this looks good. I have some pretty sweeping changes coming up in the branch I'm working on locally to address #72 but I think if you merge this I can then make those changes (mostly naming), and you can indicate which of these should be chapters in that issue.

If you want to indicate which ones are chapters in this PR, you can update the ones you want with front-matter, adding `tags: [chapter]`

2024-09-26 21:38 UTC, jazzdrive3 commented
This should be fine as-is, with no changes. Everything works as a chapter for this one.

2024-09-26 22:37 UTC, merged